# Generated by Django 6.0.5 on 2026-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
